### ISSUE TITLE
dotgit update hangs

### ISSUE THREAD

**Issue by sajattack** [kobus-v-schoor/dotgit#11]
When I run dotgit update, it hangs, when I run dotgit verbose update, it gets to the end of my filelist and then hangs

**Comment by sajattack** [comment]
Here is my filelist
```
.bashrc
.bash_profile
.gitconfig
.conkycolors
.vmail
.irssi
.zshrc
.vim
.vimrc
.config/i3
.config/albert 
.config/qutebrowser
.config/radiotray-ng
.config/hexchat
```

**Comment by kobus-v-schoor** [comment]
Would you mind posting the output of `dotgit verbose update` please?

**Comment by sajattack** [comment]
http://termbin.com/keug

**Comment by kobus-v-schoor** [comment]
Thanks - can you maybe try removing `.vim` from your filelist? It might be one of two things: 1) The git repos inside your vim folder might be causing problems since the dotgit repo is already a git repository, or 2) There is a loop checking for category/filelist conflicts that might be running for a long time due to the large number of files.

As a side-note, if you are using a plugin manager for vim it is actually unnecessary for you to add `.vim` to your dotfiles as your `.vim` folder can easily be re-created using your plugin manager

**Comment by sajattack** [comment]
That seems to have done the trick, thanks.
